"""Read-only content for the in-app FINAL V2 academic presentation."""
from __future__ import annotations

import json
from copy import deepcopy
from functools import lru_cache

from config import BASE_DIR


VALIDATION_PATH = BASE_DIR / "data" / "reference" / "final_v2_metrics.json"


@lru_cache(maxsize=1)
def final_v2_metrics():
    """Load metrics captured from the isolated FINAL V2 notebook run."""
    try:
        return json.loads(VALIDATION_PATH.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


EN_SLIDES = [
    {"type": "cover", "eyebrow": "Graduation Project", "title": "EduGuard AI", "subtitle": "Student Academic Risk Early Warning System", "meta": ["Machine Learning / AI Decision Support System", "NTI Graduation Project"], "body": "An academic early-warning system for evidence-based advisor support."},
    {"type": "idea", "title": "Project idea", "lead": "EduGuard AI is an early-warning decision-support system for universities.", "points": ["Identify students who may be academically at risk before the problem becomes severe.", "Estimate dropout risk from information available by the end of Semester 1.", "Give academic advisors an earlier, explainable basis for supportive intervention."], "diagram": ["Student information", "Estimated risk", "Advisor support"]},
    {"type": "problem", "title": "Problem statement", "lead": "Universities need a practical way to focus limited advising time on students who may need support first.", "points": ["Struggling students may be identified only after important opportunities for support have passed.", "Academic and financial indicators can provide an earlier warning signal.", "Manual monitoring becomes difficult as the number of students grows.", "Advisors need a data-driven support tool while retaining human judgment."], "question": "Can information available by the end of Semester 1 identify students at risk of dropout?"},
    {"type": "objectives", "title": "Project objectives", "lead": "The project combines a validated machine-learning workflow with a usable advisor interface.", "objectives": ["Build an early-warning machine-learning model.", "Predict dropout risk using data available by Semester 1.", "Prevent future-data leakage during model development.", "Provide calibrated risk scores rather than an uncalibrated ranking only.", "Explain individual predictions and generate advisor recommendations.", "Deliver a web-based decision-support system for analysis and reporting."]},
    {"type": "scope", "title": "System scope", "lead": "EduGuard supports academic review; it does not replace an academic decision-maker.", "does": ["Estimate dropout risk", "Explain influential model inputs", "Rank students for review", "Support advisor follow-up"], "does_not": ["Automatically expel students", "Make final academic decisions", "Prove that a factor caused dropout"], "callout": "Decision Support System"},
    {"type": "dataset", "title": "Dataset", "lead": "The source contains demographic, admission, academic, financial and economic variables.", "source": "UCI Machine Learning Repository", "why": "The dataset provides a documented higher-education context for evaluating an early-warning approach."},
    {"type": "target", "title": "Target preparation", "lead": "The three original outcomes are separated into resolved training labels and a current-student scoring cohort.", "resolved": ["Graduate", "0", "Dropout", "1"], "unresolved": "Enrolled", "note": "Enrolled is excluded from supervised training because it is not a resolved final outcome. After training, Enrolled students are scored by the model.", "why": "This keeps the training target tied to outcomes that are known and resolved."},
    {"type": "leakage", "title": "Early-warning design and data leakage", "lead": "The prediction point is the end of Semester 1.", "allowed": ["Enrollment information", "Admission and background information", "Financial and economic context", "Semester-1 performance"], "excluded": ["Semester-2 credited units", "Semester-2 enrolled units", "Semester-2 evaluations", "Semester-2 approved units", "Semester-2 grade", "Semester-2 units without evaluation"], "note": "Semester-2 variables contain future information relative to the decision point. Keeping them would make evaluation unrealistically strong.", "why": "Removing future information makes the early-warning experiment match the information available when an advisor would act."},
    {"type": "preprocessing", "title": "Data preprocessing", "lead": "The validation workflow checks data quality before fitting any candidate model.", "pipeline": ["Raw data", "Quality check", "Duplicate check", "Invalid-value validation", "Feature typing", "Encoding", "Scaling where required"], "points": ["Categorical features are One-Hot Encoded.", "Numeric missing values use median imputation.", "Categorical missing values use most-frequent imputation."], "why": "A fixed preprocessing pipeline applies the same data preparation rules during training and inference."},
    {"type": "outliers", "title": "Outlier handling", "lead": "Outlier detection is used to inspect values, not to delete students mechanically.", "points": ["IQR analysis identified many extreme observations.", "Older students, unusual unit counts and extreme but valid grades can be legitimate records.", "Impossible values are treated as missing and validated before modeling.", "Valid extreme observations remain in the dataset."], "methods": ["Logistic Regression: RobustScaler", "Tree models: original numeric scale"], "why": "RobustScaler uses the median and IQR, so it is less affected by extreme values; tree models do not require scaling."},
    {"type": "imbalance", "title": "Class imbalance", "lead": "The resolved outcomes are not perfectly balanced, so the training objective accounts for class frequency.", "handling": ["class_weight for Logistic Regression, Random Forest and Extra Trees", "scale_pos_weight for XGBoost"], "why": "Class weighting preserves real student records while giving the positive Dropout class appropriate influence.", "smote": "SMOTE was not required: class weighting was sufficient and avoids creating synthetic student records."},
    {"type": "models", "title": "Models evaluated", "lead": "Four complementary classifiers were compared with the same evaluation design.", "model_notes": [["Logistic Regression", "Simple, interpretable baseline"], ["Random Forest", "Non-linear ensemble"], ["Extra Trees", "High-randomness ensemble comparison"], ["XGBoost", "Gradient boosting model for tabular data"]], "why": "Comparing a linear baseline with three tree ensembles tests whether non-linear relationships improve early-warning performance."},
    {"type": "selection", "title": "Model selection and cross-validation", "lead": "Model selection uses five-fold Stratified Cross-Validation on the resolved training population.", "selection_metric": "PR-AUC", "points": ["Stratification preserves the Graduate/Dropout class distribution in each fold.", "PR-AUC focuses on the positive Dropout class and is informative under class imbalance.", "XGBoost achieved the strongest cross-validated PR-AUC and was selected."], "note": "There is a moderate Train-to-CV gap of approximately 5.9 percentage points, while validation and untouched test performance remain strong.", "why": "Stratified cross-validation preserves class proportions across folds; PR-AUC focuses evaluation on the positive Dropout class under class imbalance."},
    {"type": "calibration", "title": "Probability calibration and threshold", "lead": "The selected model is calibrated so the displayed score is easier to interpret as estimated risk.", "calibrator": "Isotonic Regression", "points": ["High-risk threshold: selected to meet a minimum target Recall of 85%.", "Medium-risk threshold: 30%.", "Human-review margin: ±8 percentage points around the high-risk threshold."], "why": "Calibration improves the interpretation of probabilities; threshold tuning makes the early-warning system sensitive to the positive class."},
    {"type": "performance", "title": "Final test results", "lead": "These values come from the untouched FINAL V2 test split after model selection and calibration.", "why": "Recall is emphasized because missing a student who may need support can be more costly than reviewing additional false-positive cases."},
    {"type": "evaluation", "title": "Model evaluation", "lead": "The final test probabilities were evaluated with threshold, ranking and calibration views.", "labels": ["Confusion Matrix", "ROC Curve", "Precision–Recall Curve", "Calibration Curve", "95% Confidence Intervals"], "interpretation": "The stored curves and intervals are derived from the executed FINAL V2 run; no curve points are invented for the presentation."},
    {"type": "explainability", "title": "Feature importance and explainability", "lead": "Global importance and local contribution answer different questions about the model.", "definitions": [["Permutation Importance", "Global effect on model performance when a feature is shuffled."], ["SHAP", "Contribution of features to an individual or global prediction."], ["Caution", "A model contribution does not prove causation."]], "features": ["Curricular units 1st sem (approved)", "Curricular units 1st sem (enrolled)", "Tuition fees up to date", "Course", "Curricular units 1st sem (grade)", "Scholarship holder", "Debtor"], "why": "Using both global and local explanations helps an advisor understand model behavior without presenting it as a causal finding."},
    {"type": "enrolled", "title": "Risk scoring current students", "lead": "The trained model scores the current Enrolled cohort after supervised training is complete.", "note": "The Medium-risk band exists, but no student in this scored cohort falls inside that calibrated probability interval. This is a cohort result, not a system error."},
    {"type": "recommendations", "title": "Advisor recommendation engine", "lead": "EduGuard connects the risk estimate to observable, actionable academic and financial signals.", "steps": ["Risk score", "Explanation", "Actionable signals", "Advisor recommendation"], "actions": ["Targeted tutoring", "Advisor meeting", "Missed-assessment review", "Financial support", "Payment-plan review"], "note": "Sensitive characteristics are not used as intervention reasons."},
    {"type": "conclusion", "title": "Complete system and conclusion", "lead": "The result is an end-to-end academic decision-support workflow.", "system": ["Dataset", "ML model", "Calibrated risk", "SHAP explanation", "Advisor recommendations", "Flask application", "Dashboard / reports / bulk upload"], "conclusion": "EduGuard demonstrates that information available by the end of Semester 1 can provide a strong early-warning signal for student dropout risk.", "closing": "Earlier detection. Explainable estimates. Actionable advisor support."},
]


AR_SLIDES = [
    {"type": "cover", "eyebrow": "مشروع التخرج", "title": "EduGuard AI", "subtitle": "نظام الإنذار المبكر للمخاطر الأكاديمية للطلاب", "meta": ["نظام دعم قرار باستخدام تعلم الآلة والذكاء الاصطناعي", "مشروع تخرج NTI"], "body": "نظام أكاديمي للإنذار المبكر ودعم المرشدين بقرارات قائمة على الأدلة."},
    {"type": "idea", "title": "فكرة المشروع", "lead": "EduGuard AI هو نظام لدعم القرار والإنذار المبكر في الجامعات.", "points": ["التعرف على الطلاب الذين قد يواجهون خطرًا أكاديميًا قبل تفاقم المشكلة.", "تقدير مخاطر الانسحاب باستخدام المعلومات المتاحة حتى نهاية الفصل الدراسي الأول.", "تزويد المرشد الأكاديمي أساسًا مبكرًا وقابلًا للتفسير للتدخل الداعم."], "diagram": ["بيانات الطالب", "المخاطر المقدّرة", "دعم المرشد"]},
    {"type": "problem", "title": "مشكلة البحث", "lead": "تحتاج الجامعات إلى طريقة عملية لتركيز وقت الإرشاد المحدود على الطلاب الذين قد يحتاجون إلى الدعم أولًا.", "points": ["قد يتم اكتشاف تعثر الطلاب بعد فوات فرص مهمة للدعم.", "يمكن أن توفر المؤشرات الأكاديمية والمالية إنذارًا مبكرًا.", "تصبح المتابعة اليدوية صعبة مع زيادة عدد الطلاب.", "يحتاج المرشدون إلى أداة قائمة على البيانات مع الحفاظ على الحكم البشري."], "question": "هل يمكن استخدام المعلومات المتاحة حتى نهاية الفصل الدراسي الأول للتعرف على الطلاب المعرضين لخطر الانسحاب؟"},
    {"type": "objectives", "title": "أهداف المشروع", "lead": "يجمع المشروع بين سير عمل موثوق لتعلم الآلة وواجهة عملية للمرشد الأكاديمي.", "objectives": ["بناء نموذج تعلم آلة للإنذار المبكر.", "توقع مخاطر الانسحاب باستخدام بيانات الفصل الدراسي الأول.", "منع تسرب بيانات المستقبل أثناء التطوير.", "تقديم درجات مخاطر معايرة بدلًا من ترتيب غير معاير فقط.", "تفسير التنبؤات الفردية وتوليد توصيات للمرشد.", "تقديم نظام ويب لدعم القرار والتحليل والتقارير."]},
    {"type": "scope", "title": "نطاق النظام", "lead": "يدعم EduGuard المراجعة الأكاديمية ولا يحل محل صاحب القرار الأكاديمي.", "does": ["تقدير مخاطر الانسحاب", "تفسير المدخلات المؤثرة في النموذج", "ترتيب الطلاب للمراجعة", "دعم متابعة المرشد"], "does_not": ["فصل الطلاب تلقائيًا", "اتخاذ القرارات الأكاديمية النهائية", "إثبات أن عاملًا ما تسبب في الانسحاب"], "callout": "نظام لدعم القرار"},
    {"type": "dataset", "title": "بيانات الدراسة", "lead": "تتضمن البيانات متغيرات ديموغرافية ومتغيرات القبول والأداء الأكاديمي والتمويل والاقتصاد.", "source": "مستودع UCI للتعلم الآلي", "why": "توفر البيانات سياقًا موثقًا للتعليم العالي لتقييم منهج الإنذار المبكر."},
    {"type": "target", "title": "إعداد الهدف", "lead": "يتم فصل الحالات النهائية الأصلية إلى تسميات تدريب محسومة ومجموعة طلاب حاليين للتقييم.", "resolved": ["خريج", "0", "منسحب من الدراسة", "1"], "unresolved": "مقيد حاليًا", "note": "يُستبعد الطلاب المقيدون من التدريب الخاضع للإشراف لأن حالتهم ليست نتيجة نهائية محسومة. بعد التدريب، يقيّم النموذج الطلاب المقيدين.", "why": "يربط هذا الإجراء هدف التدريب بنتائج معروفة ومحسومة."},
    {"type": "leakage", "title": "تصميم الإنذار المبكر ومنع تسرب البيانات", "lead": "تحدث عملية التنبؤ في نهاية الفصل الدراسي الأول.", "allowed": ["معلومات الالتحاق", "معلومات القبول والخلفية", "السياق المالي والاقتصادي", "أداء الفصل الدراسي الأول"], "excluded": ["الوحدات المحتسبة في الفصل الثاني", "الوحدات المسجلة في الفصل الثاني", "تقييمات الفصل الثاني", "الوحدات المجتازة في الفصل الثاني", "درجة الفصل الثاني", "وحدات الفصل الثاني دون تقييم"], "note": "تحتوي متغيرات الفصل الثاني على معلومات مستقبلية بالنسبة إلى نقطة القرار. استخدامها يجعل التقييم قويًا بشكل غير واقعي.", "why": "استبعاد معلومات المستقبل يجعل التجربة مطابقة للمعلومات المتاحة عند اتخاذ قرار الدعم."},
    {"type": "preprocessing", "title": "المعالجة المسبقة للبيانات", "lead": "يتحقق سير العمل من جودة البيانات قبل تدريب أي نموذج مرشح.", "pipeline": ["البيانات الخام", "فحص الجودة", "فحص التكرار", "التحقق من القيم غير الصالحة", "تحديد نوع الخصائص", "الترميز", "القياس عند الحاجة"], "points": ["يتم ترميز الخصائص الفئوية باستخدام One-Hot Encoding.", "تستخدم القيم الوسيطة لتعويض القيم الرقمية المفقودة.", "تستخدم الفئة الأكثر تكرارًا لتعويض القيم الفئوية المفقودة."], "why": "يطبق خط معالجة ثابت قواعد التحضير نفسها أثناء التدريب والاستخدام."},
    {"type": "outliers", "title": "معالجة القيم الشاذة", "lead": "يُستخدم اكتشاف القيم الشاذة لفحص البيانات، وليس لحذف الطلاب آليًا.", "points": ["كشف تحليل IQR عن عدد كبير من القيم المتطرفة.", "قد تكون أعمار بعض الطلاب أو أعداد الوحدات أو الدرجات المتطرفة صحيحة.", "تُعامل القيم المستحيلة كقيم مفقودة وتخضع للتحقق.", "تبقى الملاحظات المتطرفة الصحيحة في البيانات."], "methods": ["الانحدار اللوجستي: RobustScaler", "نماذج الأشجار: المقياس الرقمي الأصلي"], "why": "يستخدم RobustScaler الوسيط وIQR، لذلك يتأثر بدرجة أقل بالقيم المتطرفة؛ ولا تحتاج نماذج الأشجار إلى القياس."},
    {"type": "imbalance", "title": "عدم توازن الفئات", "lead": "النتائج المحسومة ليست متوازنة تمامًا، لذلك يراعي التدريب تكرار الفئات.", "handling": ["class_weight للانحدار اللوجستي وRandom Forest وExtra Trees", "scale_pos_weight لنموذج XGBoost"], "why": "يحافظ وزن الفئات على سجلات الطلاب الحقيقية ويمنح فئة الانسحاب تأثيرًا مناسبًا.", "smote": "لم تكن SMOTE مطلوبة؛ كان وزن الفئات كافيًا وتجنب إنشاء سجلات طلاب اصطناعية."},
    {"type": "models", "title": "النماذج التي تم تقييمها", "lead": "تمت مقارنة أربعة مصنفات متكاملة باستخدام تصميم التقييم نفسه.", "model_notes": [["Logistic Regression", "خط أساس بسيط قابل للتفسير"], ["Random Forest", "تجميع غير خطي"], ["Extra Trees", "مقارنة بتجميع عالي العشوائية"], ["XGBoost", "تعزيز تدريجي للبيانات الجدولية"]], "why": "تختبر مقارنة خط أساس خطي مع ثلاثة نماذج أشجار ما إذا كانت العلاقات غير الخطية تحسن الإنذار المبكر."},
    {"type": "selection", "title": "اختيار النموذج والتحقق المتقاطع", "lead": "استخدم اختيار النموذج تحققًا متقاطعًا طبقيًا من خمس طيات على مجموعة التدريب المحسومة.", "selection_metric": "PR-AUC", "points": ["يحافظ التقسيم الطبقي على توزيع فئتي التخرج والانسحاب في كل طية.", "يركز PR-AUC على فئة الانسحاب الإيجابية ويُعد مناسبًا مع عدم توازن الفئات.", "حقق XGBoost أقوى PR-AUC متقاطع وتم اختياره."], "why": "يقدر التحقق الطبقي التعميم مع الحفاظ على نسب الفئات؛ ويركز PR-AUC على الفئة التي تحتاج إلى دعم مبكر."},
    {"type": "calibration", "title": "معايرة الاحتمالات والحدود", "lead": "تمت معايرة النموذج المختار ليكون تفسير الدرجة المعروضة أقرب إلى المخاطر المقدّرة.", "calibrator": "Isotonic Regression", "points": ["حد المخاطر المرتفعة: اختير لتحقيق حد أدنى للاستدعاء قدره 85٪.", "حد المخاطر المتوسطة: 30٪.", "هامش المراجعة البشرية: ±8 نقاط مئوية حول حد المخاطر المرتفعة."], "why": "تحسن المعايرة تفسير الاحتمالات؛ ويجعل ضبط العتبة النظام أكثر حساسية للفئة الإيجابية."},
    {"type": "performance", "title": "النتائج النهائية للاختبار", "lead": "تأتي هذه القيم من مجموعة اختبار FINAL V2 غير المستخدمة بعد اختيار النموذج والمعايرة.", "why": "يحظى الاستدعاء باهتمام خاص لأن تفويت طالب قد يحتاج إلى الدعم قد يكون أكثر تكلفة من مراجعة حالات إيجابية كاذبة إضافية."},
    {"type": "evaluation", "title": "تقييم النموذج", "lead": "تم تقييم احتمالات الاختبار النهائية باستخدام مصفوفة الالتباس ومنحنيات الترتيب والمعايرة.", "labels": ["مصفوفة الالتباس", "منحنى ROC", "منحنى Precision–Recall", "منحنى المعايرة", "فواصل الثقة 95٪"], "interpretation": "تم اشتقاق المنحنيات والفواصل المخزنة من تشغيل FINAL V2 الفعلي؛ ولم تتم إضافة نقاط منحنيات مختلقة."},
    {"type": "explainability", "title": "أهمية الخصائص وقابلية التفسير", "lead": "تجيب الأهمية العامة والمساهمة المحلية عن سؤالين مختلفين حول سلوك النموذج.", "definitions": [["Permutation Importance", "الأثر العام على أداء النموذج عند تبديل قيم الخاصية."], ["SHAP", "مساهمة الخصائص في تنبؤ فردي أو في النموذج عمومًا."], ["تنبيه", "مساهمة النموذج لا تثبت علاقة سببية."]], "features": ["الوحدات المجتازة في الفصل الأول", "الوحدات المسجلة في الفصل الأول", "انتظام المصروفات الدراسية", "التخصص", "درجة الفصل الأول", "الحصول على منحة", "وجود مستحقات مالية"], "why": "يساعد الجمع بين التفسير العام والمحلي المرشد على فهم سلوك النموذج دون عرضه كاكتشاف سببي."},
    {"type": "enrolled", "title": "تقييم مخاطر الطلاب المقيدين حاليًا", "lead": "يقيّم النموذج المدرب مجموعة الطلاب المقيدين بعد اكتمال التدريب الخاضع للإشراف.", "note": "توجد فئة المخاطر المتوسطة في النظام، لكن لا يقع أي طالب في هذه المجموعة داخل مجال الاحتمال المعاير لها. هذه نتيجة للمجموعة وليست خطأ في النظام."},
    {"type": "recommendations", "title": "محرك توصيات المرشد الأكاديمي", "lead": "يربط EduGuard تقدير المخاطر بإشارات أكاديمية ومالية قابلة للتدخل.", "steps": ["درجة المخاطر", "التفسير", "الإشارات القابلة للتدخل", "توصية المرشد"], "actions": ["دعم دراسي موجه", "اجتماع مع المرشد", "مراجعة التقييمات الفائتة", "دعم مالي", "مراجعة خطة السداد"], "note": "لا تستخدم الخصائص الحساسة كأسباب للتدخل."},
    {"type": "conclusion", "title": "النظام الكامل والخلاصة", "lead": "النتيجة هي سير عمل متكامل لدعم القرار الأكاديمي.", "system": ["البيانات", "نموذج تعلم الآلة", "المخاطر المعايرة", "تفسير SHAP", "توصيات المرشد", "تطبيق Flask", "لوحة التحكم والتقارير والرفع الجماعي"], "conclusion": "يوضح EduGuard أن المعلومات المتاحة حتى نهاية الفصل الدراسي الأول يمكن أن تقدم إشارة إنذار مبكر قوية لمخاطر انسحاب الطلاب.", "closing": "اكتشاف أبكر. تقديرات قابلة للتفسير. دعم عملي للمرشد."},
]


UI = {
    "en": {"previous": "Previous", "next": "Next", "fullscreen": "Fullscreen", "exit_fullscreen": "Exit fullscreen", "slide": "Slide", "of": "of", "keyboard": "Arrow keys or Space", "present": "Presentation mode", "back": "Back to dashboard", "controls": "Presentation controls", "dataset_students": "students", "input_features": "original input features", "outcomes": "original outcomes", "graduate": "Graduate", "dropout": "Dropout", "enrolled": "Enrolled", "train_pr": "Train PR-AUC", "cv_pr": "CV PR-AUC", "gap": "Gap", "accuracy": "Accuracy", "precision": "Precision", "recall": "Recall", "f1": "F1", "pr_auc": "PR-AUC", "roc_auc": "ROC-AUC", "brier": "Brier Score", "low": "Low", "medium": "Medium", "high": "High", "human_review": "Human review", "threshold": "High-risk threshold", "review_margin": "Review margin", "estimated_risk": "Estimated dropout risk", "students": "students", "count": "Count", "rate": "Rate", "feature": "Feature", "importance": "Mean |SHAP|", "status": "Selected model", "why": "Why this method?", "actual": "Actual", "predicted": "Predicted", "true_graduate": "True Graduate", "false_alert": "False alert", "missed_dropout": "Missed dropout", "true_dropout": "True Dropout", "permutation": "Permutation importance", "shap": "SHAP contribution"},
    "ar": {"previous": "السابق", "next": "التالي", "fullscreen": "ملء الشاشة", "exit_fullscreen": "إنهاء ملء الشاشة", "slide": "الشريحة", "of": "من", "keyboard": "أسهم لوحة المفاتيح أو المسافة", "present": "وضع العرض", "back": "العودة إلى لوحة التحكم", "controls": "عناصر تحكم العرض", "dataset_students": "طالب", "input_features": "خاصية إدخال أصلية", "outcomes": "حالات نهائية أصلية", "graduate": "خريج", "dropout": "منسحب من الدراسة", "enrolled": "مقيد حاليًا", "train_pr": "PR-AUC للتدريب", "cv_pr": "CV PR-AUC", "gap": "الفجوة", "accuracy": "الدقة العامة", "precision": "الدقة الإيجابية", "recall": "الاستدعاء", "f1": "مقياس F1", "pr_auc": "PR-AUC", "roc_auc": "ROC-AUC", "brier": "Brier Score", "low": "منخفض", "medium": "متوسط", "high": "مرتفع", "human_review": "مراجعة بشرية", "threshold": "حد المخاطر المرتفعة", "review_margin": "هامش المراجعة", "estimated_risk": "مخاطر الانسحاب المقدّرة", "students": "طالب", "count": "العدد", "rate": "النسبة", "feature": "الخاصية", "importance": "متوسط |SHAP|", "status": "النموذج المختار", "why": "لماذا هذه الطريقة؟", "actual": "الفعلي", "predicted": "المتوقع", "true_graduate": "خريج صحيح", "false_alert": "إنذار خاطئ", "missed_dropout": "انسحاب فائت", "true_dropout": "انسحاب صحيح", "permutation": "أهمية التبديل", "shap": "مساهمة SHAP"},
}


def presentation_payload(model):
    """Build presentation-only data without modifying model, database, or language state."""
    metrics = deepcopy(final_v2_metrics())
    source = getattr(model, "source", None)
    counts = source.get("Target").value_counts().to_dict() if source is not None and "Target" in source else {}
    dataset = {
        "total_students": int(sum(counts.values())),
        "input_features": int(len(source.columns) - 1) if source is not None and not source.empty else 36,
        "outcomes": {str(key): int(value) for key, value in counts.items()},
        "operational_features": int(len(getattr(model, "features", []))),
        "excluded_future_features": int(len(metrics.get("excluded_future_features", []))),
    }
    return {"metrics": metrics, "dataset": dataset, "ui": UI, "slides": {"en": EN_SLIDES, "ar": AR_SLIDES}}
